---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html/datespan.com
    - /bin/mkdir -p $DEPLOYPATH/scripts
    - /bin/mkdir -p $DEPLOYPATH/styles
    - /bin/mkdir -p $DEPLOYPATH/images
    - /bin/cp index.htm $DEPLOYPATH/
    - /bin/cp scripts/addDatePicker.js $DEPLOYPATH/scripts/
    - /bin/cp scripts/humanSpan.js $DEPLOYPATH/scripts/
    - /bin/cp scripts/moment.min.js $DEPLOYPATH/scripts/
    - /bin/cp styles/bootstrap.min.css $DEPLOYPATH/styles/
    - /bin/cp styles/DateSpan.css $DEPLOYPATH/styles/
    - /bin/cp -r images/ $DEPLOYPATH/images/
